services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiktok-api:latest
    container_name: tiktok-api
    ports:
      - "8080:8080"
    environment:
      - CREDENTIALS_FILE_PATH=/app/config/cjf.json
    volumes:
      - /home/petd/ggdirve/cjf.json:/app/config/cjf.json
    depends_on:
      - maven-build
    restart: unless-stopped

  maven-build:
    image: maven:3.8.6-openjdk-17
    volumes:
      - .:/build
      - ~/.m2:/root/.m2
    command: mvn clean package -DskipTests
    profiles:
      - build